####
#### this Dockerfile is used to build a mysql image with prepared data in it
####

FROM mysql:5.7

####
#### this Dockerfile is used to build a mysql image with prepared data in it
####

ARG data_directory
ADD $data_directory/mysql /var/lib/mysql
